services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bullseye
    command: sleep infinity
    working_dir: /workspaces
    volumes:
      - ..:/workspaces/boot-webserver:cached,Z
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gator
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
